In [1]:
from tensorflow import keras

# Loading the model

In [2]:
model = keras.models.load_model('model_v1.h5')

In [3]:
model.summary()

Model: "model_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_29 (InputLayer)        [(None, 273)]             0         
_________________________________________________________________
dense_133 (Dense)            (None, 150)               41100     
_________________________________________________________________
dense_134 (Dense)            (None, 50)                7550      
_________________________________________________________________
Feature_latent (Dense)       (None, 10)                510       
_________________________________________________________________
dense_135 (Dense)            (None, 50)                550       
_________________________________________________________________
dense_136 (Dense)            (None, 150)               7650      
_________________________________________________________________
dense_137 (Dense)            (None, 273)               412

In [4]:

layer_name = 'Feature_latent'
intermediate_layer_model = keras.Model(inputs=model.input,
                                       outputs=model.get_layer(layer_name).output)


# Encoding for single datapoint

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('processed_dataset.csv')

In [7]:
df.head()

Unnamed: 0        0        1        2        3         4         5  \
0           0  243.000  350.200  897.400  677.800  3712.600  2422.400   
1           1  171.400  226.600  450.800  360.800  3567.600  1593.600   
2           2  234.000  298.000  668.000  448.000  3997.000  1864.000   
3           3  317.000  317.000  622.000  297.000  4837.000  2005.000   
4           4  141.133  203.936  488.792  288.667  2341.268  1015.778   

          6        7        8  ...       265      266      267      268  \
0  1337.000  252.800  338.800  ...  2919.400  540.400  599.800  891.600   
1   752.000  156.600  228.600  ...  1739.600  384.000  475.800  790.000   
2   953.000  136.000  221.000  ...  3022.000  341.000  507.000  921.000   
3   756.000   70.000   94.000  ...  1225.000  231.000  317.000  595.000   
4   454.481  235.149  335.514  ...  1226.434  399.925  521.716  851.474   

        269       270       271       272       273       274  
0  1279.400  2161.200  3015.400  2568.000  0.385535  0.546250  
1  1026.400  2397.200  2234.200  1719.400  0.520737  0.679225  
2  1405.000  2423.000  3613.000  2983.000  0.424557  0.578246  
3   612.000  2406.000  1808.000  1066.000  0.732383  0.842036  
4   788.311  1905.576  1387.545   861.357  0.571616  0.721583  

[5 rows x 276 columns]

In [8]:
X_data = df.drop(['Unnamed: 0','273','274'],axis=1, inplace=False)

In [9]:
X_data = X_data/1000

In [10]:
X_data.shape

(2947, 273)

In [11]:
X_data = np.array(X_data)

In [12]:
X_data.shape

(2947, 273)

In [13]:
X_1 = X_data[0]

In [14]:
X_1.shape

(273,)

In [15]:
X_1 = np.expand_dims(X_1, axis=0)

In [16]:
X_1.shape

(1, 273)

In [17]:
intermediate_output = intermediate_layer_model(X_1)

In [18]:
intermediate_output

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[ 1.3717824 ,  1.1191478 ,  2.4690793 ,  3.1649635 ,  2.75314   ,
        -0.9286842 , -0.47839576,  1.8618125 ,  8.483896  ,  0.02696992]],
      dtype=float32)>

# Encoding the whole dataset

In [19]:
intermediate_output = intermediate_layer_model(X_data)

In [20]:
intermediate_output.shape

TensorShape([2947, 10])

In [21]:
import tensorflow as tf
intermediate_output_np = intermediate_output.numpy()

In [22]:
intermediate_output_np

array([[ 1.3717823 ,  1.1191477 ,  2.4690788 , ...,  1.8618144 ,
         8.483894  ,  0.02696972],
       [ 0.69577676,  0.4719947 ,  0.8782271 , ...,  1.4433293 ,
         5.3137383 ,  0.30663761],
       [ 0.53508306,  0.74585783,  2.8816214 , ...,  0.3658805 ,
         8.386508  , -0.22823203],
       ...,
       [ 1.1877071 , -0.4342877 ,  0.65518695, ...,  0.9251185 ,
         2.2819278 ,  0.7056834 ],
       [ 0.5040876 , -0.07960146, -0.36556542, ...,  0.15845701,
         2.1693914 , -0.65187347],
       [ 0.44544372,  0.02776576,  0.7267449 , ...,  0.5472965 ,
         2.454513  , -1.0466843 ]], dtype=float32)

In [23]:
intermediate_output_np.shape

(2947, 10)

In [24]:
cols = intermediate_output_np.shape[1]

In [25]:
cols

10

In [26]:
index_values = [i for i in range (intermediate_output_np.shape[0])]
len(index_values)

2947

In [27]:
column_values  = [i for i in range (intermediate_output_np.shape[1])]
len(column_values)

10

In [28]:
df_encoded = pd.DataFrame(data = intermediate_output_np, 
                  index = index_values, 
                  columns = column_values)

In [29]:
df_encoded

0         1         2         3         4         5         6  \
0     1.371782  1.119148  2.469079  3.164964  2.753141 -0.928685 -0.478396   
1     0.695777  0.471995  0.878227  2.781074  2.894665 -0.336990  0.175473   
2     0.535083  0.745858  2.881621  2.780188  2.232395 -0.426074 -0.336759   
3    -0.026857  0.098330  1.059372  2.443299  3.532076  0.864627 -0.165695   
4     1.286062  0.822033  0.607374  2.285303  2.499143 -0.602961 -0.222075   
...        ...       ...       ...       ...       ...       ...       ...   
2942  0.749474 -0.181962  0.440250  1.545387  3.097845  0.222938  0.091134   
2943  1.246725  0.072085  0.813656  1.651416  3.228261 -0.621067 -0.019703   
2944  1.187707 -0.434288  0.655187  2.047939  2.747905 -0.557238 -0.582953   
2945  0.504088 -0.079601 -0.365565  2.642547  1.700682 -0.666713 -0.822734   
2946  0.445444  0.027766  0.726745  3.000825  1.585884 -0.465326  0.373297   

             7         8         9  
0     1.861814  8.483894  0.026970  
1     1.443329  5.313738  0.306638  
2     0.365880  8.386508 -0.228232  
3     0.146986  3.512267  0.124011  
4     0.405282  3.419030 -0.756155  
...        ...       ...       ...  
2942 -0.120250  2.500812 -0.222808  
2943  0.594698  2.494640 -0.476267  
2944  0.925119  2.281928  0.705683  
2945  0.158457  2.169391 -0.651873  
2946  0.547297  2.454513 -1.046684  

[2947 rows x 10 columns]

In [30]:
df_encoded['gt_ndvi'] = df['273']

In [31]:
df_encoded['gt_msavi2'] = df['274']

In [32]:
df_encoded

0         1         2         3         4         5         6  \
0     1.371782  1.119148  2.469079  3.164964  2.753141 -0.928685 -0.478396   
1     0.695777  0.471995  0.878227  2.781074  2.894665 -0.336990  0.175473   
2     0.535083  0.745858  2.881621  2.780188  2.232395 -0.426074 -0.336759   
3    -0.026857  0.098330  1.059372  2.443299  3.532076  0.864627 -0.165695   
4     1.286062  0.822033  0.607374  2.285303  2.499143 -0.602961 -0.222075   
...        ...       ...       ...       ...       ...       ...       ...   
2942  0.749474 -0.181962  0.440250  1.545387  3.097845  0.222938  0.091134   
2943  1.246725  0.072085  0.813656  1.651416  3.228261 -0.621067 -0.019703   
2944  1.187707 -0.434288  0.655187  2.047939  2.747905 -0.557238 -0.582953   
2945  0.504088 -0.079601 -0.365565  2.642547  1.700682 -0.666713 -0.822734   
2946  0.445444  0.027766  0.726745  3.000825  1.585884 -0.465326  0.373297   

             7         8         9   gt_ndvi  gt_msavi2  
0     1.861814  8.483894  0.026970  0.385535   0.546250  
1     1.443329  5.313738  0.306638  0.520737   0.679225  
2     0.365880  8.386508 -0.228232  0.424557   0.578246  
3     0.146986  3.512267  0.124011  0.732383   0.842036  
4     0.405282  3.419030 -0.756155  0.571616   0.721583  
...        ...       ...       ...       ...        ...  
2942 -0.120250  2.500812 -0.222808  0.707826   0.825318  
2943  0.594698  2.494640 -0.476267  0.699463   0.820091  
2944  0.925119  2.281928  0.705683  0.694561   0.817328  
2945  0.158457  2.169391 -0.651873  0.680096   0.806699  
2946  0.547297  2.454513 -1.046684  0.678625   0.805381  

[2947 rows x 12 columns]

In [33]:
df_encoded.to_csv('encoded_dataset.csv')